linioexp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

# Mapeo entre endpoints de la web / direcciones url y las vistas en el archivo views.py
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('productos', views.ProductListView.as_view(), name='product-list'),
    path('productos/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('add_to_cart/<int:product_pk>', views.AddToCartView.as_view(), name='add-to-cart'),
    path('remove_from_cart/<int:product_pk>', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('carrito/', views.PedidoDetailView.as_view(), name='pedido-detail'),
    path('pedido/<int:pedido_pk>', views.PedidoDetailView.as_view(), name='paid-pedido-detail'),
    path('checkout/<int:pk>', views.PedidoUpdateView.as_view(), name='pedido-update'),
    path('payment/', views.PaymentView.as_view(), name='payment'),
    path('complete_payment/', views.CompletePaymentView.as_view(), name='complete-payment'),
    path('registro/', views.RegistrationView.as_view(), name='register'),
    path('empty_car/', views.empty_car, name='empty-car'),
    path('no_client/', views.no_client, name='no-client'),
    path('invalid_age/', views.invalid_age, name='invalid-age'),
    path('invalid_dni/', views.invalid_dni, name='invalid-dni'),
    path('invalid_ruc/', views.invalid_ruc, name='invalid-ruc'),
    path('invalid_phone/', views.invalid_phone, name='invalid-phone'),
    path('invalid_price/', views.invalid_price, name='invalid-price'),
    path('invalid_discount/', views.invalid_discount, name='invalid-discount'),
    path('register_commerce/', views.RegisterCommerceView.as_view(),name='registar-comercio'),
    path('register_product/', views.RegisterProductView.as_view(), name='registar-producto'),
    path('edit_product/<int:pk>', views.EditProductView.as_view(), name='editar-producto'),
    path('pedidos', views.PedidoListView.as_view(), name='pedido-list'),
    path('cancel_pedido/<int:pedido_pk>', views.DeletePedido.as_view(), name='cancelar-pedido'),
    path('register_comment/<int:pedido_pk>', views.RegisterCommentView.as_view(), name='registrar-comentario'),
    path('deliver_pedido/<int:pedido_pk>', views.PedidoDeliveredView.as_view(), name='pedido-delivered')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
import datetime

"""
Los modelos de la aplicacion
"""

# Create your models here.
# Modelo Perfil
class Profile(models.Model):
    ####
    # Relacion con el modelo User de Django (uno a uno)
    # ondelete=CASCADE indica que al eliminar un usuario, se elimina
    # cualquier dato relacionado con este
    ####
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Atributos adicionales para el usuario
    # DNI: Campo string, con longitud maxima 8
    documento_identidad = models.CharField(max_length=8)
    # Fecha de nacimiento: Campo fecha
    fecha_nacimiento = models.DateField()
    # Estado: Campo string, con longitud maxima 3
    estado = models.CharField(max_length=3)

    ## Opciones de genero
    MASCULINO = 'MA'
    FEMENINO = 'FE'
    NO_BINARIO = 'NB'
    GENERO_CHOICES = [
        (MASCULINO, 'Masculino'),
        (FEMENINO, 'Femenino'),
        (NO_BINARIO, 'No Binario')
    ]
    # Genero: Campo string, con longitud maxima 2 y cuyo valor debe estar en la lista GENERO_CHOICES
    genero = models.CharField(max_length=2, choices=GENERO_CHOICES)

    # Al hacer print, se muestra el campo usuario
    def __str__(self):
        return self.user.get_username()


    # Metodo de validacion
    def validate_data(self):
        now = datetime.datetime.now()
        # Restamos la fecha actual con la de nacimiento para obtener la edad
        edad = int((now.date()-self.fecha_nacimiento).days/365.25) - ((now.month, now.day) < (self.fecha_nacimiento.month, self.fecha_nacimiento.day))
        if edad < 18:
            raise ValidationError(
                _('Invalid value: %(value)s. Must be over 18'),
                params={'value': str(edad)},
            )

        if(len(self.documento_identidad)!=8):
            raise ValidationError(
                _('Invalid value: %(value)s. DNI must be 8 characters'),
                params={'value': str(len(self.documento_identidad))},
            )


# Modelo Comerciante
class Comerciante(models.Model):
    # Relacion con el modelo Perfil
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'Comerciante: {self.user_profile.user.get_username()}'

    # Registrar comercio
    def register_commerce(self, ruc, razon_social, telefono):
        nuevo_proveedor = Proveedor.objects.create(ruc=ruc,razon_social=razon_social, telefono=telefono, comerciante=self)
        nuevo_proveedor.save()



# Modelo Colaborador
class Colaborador(models.Model):
    # Relacion con el modelo Perfil
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

    # Atributos especificos del Colaborador
    # Reputacion: Campo tipo flotante
    reputacion = models.FloatField()
    #####
    # Relacion con el modelo Localizacion (many to many)
    # Un colaborador puede estar asignado a varias localizaciones
    # y una localizacion puede estar asingada a varios colaboradores
    #####
    cobertura_entrega = models.ManyToManyField(to='Localizacion')

    def __str__(self):
        return f'Colaborador: {self.user_profile.user.get_username()}'


# Modelo Localizacion
class Localizacion(models.Model):
    # Distrito: Campo string, longitud maxima de 20 caracters
    distrito = models.CharField(max_length=20)
    # Provincia: Campo string, longitud maxima de 20 caracters
    provincia = models.CharField(max_length=20)
    # Departamento: Campo string, longitud maxima de 20 caracters
    departamento = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.distrito}, {self.provincia}, {self.departamento}'


# Modelo Cliente
class Cliente(models.Model):
    # Relacion con el modelo Perfil
    user_profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

    # Atributos especificos del Cliente
    preferencias = models.ManyToManyField(to='Categoria')

    def __str__(self):
        return f'Cliente: {self.user_profile.user.get_username()}'


# Modelo Categoria
class Categoria(models.Model):
    # Codigo: Campo string con longitud maxima 4
    codigo = models.CharField(max_length=4)
    # Nombre: Campo string con longitud maxima 20
    nombre = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.codigo}: {self.nombre}'


# Modelo Producto
class Producto(models.Model):
    ####
    # Relaciones (many to one)
    # Una categoria (o un proveedor) puede tener varios productos asignados
    # Al borrar, los modelos que dependen de este, ponen sus campos como null
    ####
    categoria = models.ForeignKey('Categoria', on_delete=models.SET_NULL, null=True)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.SET_NULL, null=True)

    # Atributos
    # Nombre: Campo string con longitud maxima 20
    nombre = models.CharField(max_length=20)
    # Descripcion: Campo tipo texto
    descripcion = models.TextField()
    # Precio: Campo tipo float
    precio = models.FloatField()
    # Estado: Campo string con longitud maxima 3
    estado = models.CharField(max_length=3)
    # Descuento: Campo tipo float con valor default 0
    descuento = models.FloatField(default=0)

    def __str__(self):
        return self.nombre

    # Retorna precio final con descuento
    def get_precio_final(self):
        return self.precio * (1 - self.descuento)

    # Retorna codigo de producto
    def sku(self):
        codigo_categoria = self.categoria.codigo.zfill(4)
        codigo_producto = str(self.id).zfill(6)

        return f'{codigo_categoria}-{codigo_producto}'

    # Metodo de validacion
    def validate_data(self):
        if self.precio<0:
            raise ValidationError(
                _('Invalid value: %(value)s. Price must be over 0'),
                params={'value': str(self.precio)},
            )

        if(self.descuento<0 or self.descuento>1):
            raise ValidationError(
                _('Invalid value: %(value)s. Discount must be over 0 and less than 1'),
                params={'value': str(self.descuento)},
            )


# Modelo ProductoImage
class ProductoImage(models.Model):
    # Relacion con la tabla producto
    product = models.ForeignKey('Producto', on_delete=models.CASCADE, related_name='images')
    # Image: Campo tipo imagen
    image = models.ImageField(upload_to="products", null=True, blank=True)


# Modelo Proveedor
class Proveedor(models.Model):
    # Comerciante
    comerciante = models.OneToOneField(Comerciante, on_delete=models.CASCADE, null=True)
    # Ruc: Campo string con longitud maxima 11
    ruc = models.CharField(max_length=11)
    # Razon social: Campo string con longitud maxima 20
    razon_social = models.CharField(max_length=20)
    #Telefono: Campo string con longitud maxima 9
    telefono = models.CharField(max_length=9)

    def __str__(self):
        return self.razon_social


    # Metodo de validacion
    def validate_data(self):
        if(len(self.telefono)!=9):
            raise ValidationError(
                _('Invalid value: %(value)s. Phone must be 9 characters'),
                params={'value': str(len(self.telefono))},
            )

        if(len(self.ruc)!=11):
            raise ValidationError(
                _('Invalid value: %(value)s. RUC must be 11 characters'),
                params={'value': str(len(self.ruc))},
            )


    def register_product(self,categoria,nombre,descripcion,precio,estado,descuento):
        producto = Producto.objects.create(categoria=categoria, nombre=nombre, descripcion=descripcion, precio=precio, estado=estado, descuento=descuento, proveedor=self)
        try:
            producto.validate_data()
        except Exception as e:
            producto.delete()
            print("error1")
            print(e)
            raise e

        return producto

    """
    def update_product(self):
        productos = self.producto_set.all()
    """


# Modelo Pedido
class Pedido(models.Model):
    # Relaciones (many to one)
    cliente = models.ForeignKey('Cliente', on_delete=models.CASCADE)
    repartidor = models.ForeignKey('Colaborador', on_delete=models.SET_NULL, null=True)
    ubicacion = models.ForeignKey('Localizacion', on_delete=models.SET_NULL, null=True)

    # Atributos
    # Fecha creacion: Campo tipo fecha_hora, automaticamente guarda la fecha en que se registra
    fecha_creacion = models.DateTimeField(auto_now=True)
    # Fecha entrega: Campo tipo fecha hora
    fecha_entrega = models.DateTimeField(blank=True, null=True)
    # Estado: Campo string con longitud maxima 3
    estado = models.CharField(max_length=3)
    # Direccion entrega: Campo string con longitud maxima 100
    direccion_entrega = models.CharField(max_length=100, blank=True, null=True)
    # Tarifa: Campo float
    tarifa = models.FloatField(blank=True, null=True)
    # Comprobante: Campo opcion multiple
    FACTURA = 'Factura'
    BOLETA = 'Boleta'
    TIPO_COMPROBANTE = [(FACTURA, 'Factura'),(BOLETA, 'Boleta')]
    comprobante = models.CharField(max_length=7, choices=TIPO_COMPROBANTE, null=True)


    def __str__(self):
        return f'{self.cliente} - {self.fecha_creacion} - {self.estado}'

    # Retorna el total de costo del pedido
    def get_total(self):
        # Obtiene el detalle dle pedido
        detalles = self.detallepedido_set.all()
        total = 0
        # Para cada elemento, suma el subtotal
        for detalle in detalles:
            total += detalle.get_subtotal()
        total += self.tarifa
        return total

    # Retorna true si se puede cancelar pedido o false, de lo contrario
    def puede_cancelar(self):
        # El pedido se puede cancelar si no hay colaborador asignado
        if self.repartidor is None:
            return True

        # El pedido se puede cancelar antes de las 12 horas
        now = datetime.datetime.now(self.fecha_creacion.tzinfo)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import Http404

from .models import *

"""
Formulario para crear un usuario
Contiene los campos requeridos y opcionales (required=False) para crear un usuario
"""
class UserForm(UserCreationForm):
    # django.contrib.auth.User attributes
    # Primer nombre: Variable string. Validacion 150 caracteres maximo
    first_name = forms.CharField(max_length=150, required=False)
    # Apellido: Variable string. Validacion 150 caracteres maximo
    last_name = forms.CharField(max_length=150, required=False)
    # Email: Variable objeto Email. Validacion 150 caracteres maximo, required=True por default
    email = forms.EmailField(max_length=150)

    # Profile attributes
    # DNI: Variable tipo string. Validacion 8 caracteres maximo, required=True por default
    documento_identidad = forms.CharField(max_length=8)
    # Fecha de nacimiento: Variable tipo date. required=True por default
    fecha_nacimiento = forms.DateField()
    # Estado: Variable tipo string. Validacion 3 caracteres maximo, required=True por default
    estado = forms.CharField(max_length=3)
    ## Opciones de genero
    MASCULINO = 'MA'
    FEMENINO = 'FE'
    NO_BINARIO = 'NB'
    GENERO_CHOICES = [
        (MASCULINO, 'Masculino'),
        (FEMENINO, 'Femenino'),
        (NO_BINARIO, 'No Binario')
    ]
    # Genero: Variable tipo seleccion multiple (combobox), required=True por default
    genero = forms.ChoiceField(choices=GENERO_CHOICES)

    # Colaborador attributes
    # Es colaborador? Variable tipo boolean (checkbox)
    is_colaborador = forms.BooleanField(required=False)
    # Reputacion: Variable tipo float
    reputacion = forms.FloatField(required=False)
    # Cobertura entrega: Variable seleccion multiple, cuya data proviene de la base de datos
    cobertura_entrega = forms.ModelChoiceField(queryset=Localizacion.objects.all(), required=False)

    # Cliente attributes
    # Es cliente? Variable tipo boolean (checkbox)
    is_cliente = forms.BooleanField(required=False)
    # Preferencias: Variable seleccion multiple, cuya data proviene de la base de datos
    preferencias = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=False)

    # Comerciatne attributes
    # Es comerciante? Variable tipo boolean (checkbox)
    is_comerciante = forms.BooleanField(required=False)

    # Modelo User y sus campos
    class Meta:
        model = User
        fields = ['username',
        'first_name',
        'last_name',
        'email',
        'documento_identidad',
        'fecha_nacimiento',
        'estado',
        'genero',
        'is_cliente',
        'preferencias',
        'is_colaborador',
        'reputacion',
        'cobertura_entrega',
        'is_comerciante'
        ]



"""
Formulario para crear un comercio
Contiene los campos requeridos y opcionales (required=False) para crear un comercio
"""
class CommerceForm(forms.Form):
    # Ruc: Variable string. Validacion 11 caracteres maximo
    ruc = forms.CharField(max_length=11)
    # Razon social: Variable string. Validacion 20 caracteres maximo
    razon_social = forms.CharField(max_length=20)
    # Telefono: Variable string. Validacion 9 caracteres maximo
    telefono = forms.CharField(max_length=9)

    # Modelo Comercio y sus campos
    class Meta:
        model = Proveedor
        fields = ['ruc',
        'razon_social',
        'telefono'
        ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(CommerceForm, self).__init__(*args, **kwargs)




"""
Formulario para crear un producto
Contiene los campos requeridos y opcionales (required=False) para crear un producto
"""
class ProductForm(forms.Form):
    # Categoria: Variable seleccion multiple.
    categoria = forms.ModelChoiceField(queryset=Categoria.objects.all(), required=False)
    # Nombre: Variable string. Validacion 20 caracteres maximo
    nombre = forms.CharField(max_length=20)
    # Descripcion: Variable texto.
    descripcion = forms.CharField()
    # Precio: Campo float con valor precio
    precio = forms.FloatField()
    # Estado: Campo string con longitud maxima 3
    estado = forms.CharField(max_length=3)
    # Descuento: Campo tipo float
    descuento = forms.FloatField(required=False)
    # Imagen
    imagen = forms.ImageField()


    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(ProductForm, self).__init__(*args, **kwargs)


# Clase para guardar comentarios (comunicacion entre proveedor y cliente)
class CommentForm(forms.Form):
    # Body: Texto del cuerpo.
    body = forms.CharField(widget=forms.Textarea)

    # Modelo Comment y sus campos
    class Meta:
        model = Comment
        fields = ['body',
        ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.pedido_pk = kwargs.pop('pedido_pk')
        super(CommentForm, self).__init__(*args, **kwargs)

main/templates/main/custom_alert.html
{% extends "base.html" %}

{% block content %}
<script>
   alert("{{mensaje}}");
   window.location.href = "/";
</script>

{% endblock %}

main/templates/main/home.html
<!-- Importa el banner que esta en base.html-->
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <!-- Empieza la vista home-->
    <p>
      <a href="{% url 'logout' %}" style="float:right;background-color:#1f252e;color:#FFFFFF;padding:6px;border-radius:4px">Cierra Sesion</a>
   </p>
    <h3 class="title"> Hola {{ user.get_username }} </h3>
    {% else %}
    <h3 class="title"> Hola </h3>
    <div class="content">
        <p>
          <div>
             <a href="{% url 'login' %}" class='button' style="background-color:#242647;color:#FFFFFF;border-color:#242647">Inicia Sesion</a>
         </div>
         <br>
         <div>
          <a href="{% url 'register' %}" class='button' style="background-color:#242647;color:#FFFFFF;border-color:#242647">Registrate</a>
          </div>
        </p>
    </div>
    {% endif %}


    <!-- Muestra mensajes si existen-->
    {% if messages %}
        {% for message in messages %}
        <div class="notification {% if message.tags %}is-{{ message.tags }}{% endif %}">
            <button class="delete"></button>
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    <hr>
    <div class="row">
      <div class="column" style="float:left;width:50%">
          <h5 class="subtitle"> Ultimos productos </h5>
          <div class="content">
              <ul>
                 <!-- Carga los ultimos productos-->
                {% for producto in latest_products %}
                  <li  style="line-height: 1.8;">
                    <a href="{% url 'product-detail' producto.pk %}">
                      {{ producto.nombre }}
                    </a>
                    - {{ producto.precio }}
                  </li>
                {% empty %}
                  <li>Aun no hay productos disponibles.</li>
                {% endfor %}
              </ul>
          </div>
      </div>
      <div class="column" style="float:left">
        {% if user.is_authenticated %}
         <div class="content">
             <a href="{% url 'pedido-detail' %}" class='button'
             style="background-color:#FF8300;color:#FFFFFF;border-color:#FF8300;font-weight:bold">
               Ver carrito
             </a>
         </div>
        {% endif %}
         {% if puede_registrar_comercio %}
          <div class="content">
              <a href="{% url 'registar-comercio' %}" class='button'
              style="background-color:#242647;color:#FFFFFF;border-color:#242647">
                Registrar comercio
              </a>
          </div>
         {% endif %}
          {% if puede_registrar_producto %}
           <div class="content">
               <a href="{% url 'registar-producto' %}" class='button'
               style="background-color:#242647;color:#FFFFFF;border-color:#242647">
                 Registrar producto
               </a>
           </div>
          {% endif %}
           {% if tiene_pedido %}
            <div class="content">
                <a href="{% url 'pedido-list' %}" class='button'
                style="background-color:#242647;color:#FFFFFF;border-color:#242647">
                  Ver pedido
                </a>
            </div>
           {% endif %}
           {% if tiene_por_entregar %}
            <div class="content">
                <a href="{% url 'pedido-list' %}" class='button'
                style="background-color:#242647;color:#FFFFFF;border-color:#242647">
                  Ver pedidos pendiente de entrega
                </a>
            </div>
           {% endif %}
         <div class="content">
            <a href="{% url 'product-list' %}" style="background-color:#242647;color:#FFFFFF;padding:12px;border-radius:7px">Ver Lista de Productos Completa</a>
         </div>
      </div>
    </div>
    <hr style="margin-top:300px">
{% endblock %}

main/templates/main/payment.html
{% extends "base.html" %}

{% block content %}
   <!-- Corre el script de paypal para hacer transferencias-->
    <script src="https://www.paypal.com/sdk/js?client-id=AYP4kgKwXotywxdXwqUwZvyfq9dr9_zZCcxtMM-g3AMTk5vXiIHRh8KtTwax5JWZQqGJRV5mcfHYazo4"> // Replace YOUR_SB_CLIENT_ID with your sandbox client ID
    </script>

    <h3 class="title">Precio total del pedido: {{ pedido.get_total }}</h3>

    <div class="block" id="paypal-button-container"></div>

    <!-- Add the checkout buttons, set up the order and approve the order -->
    <script>
      var total = {{ pedido.get_total }}

      // Agrega boton de paypal que crea una orden de compra
      paypal.Buttons({
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{
              amount: {
                value: `${total}`
              }
            }]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(details) {
            window.location.href = '../complete_payment';
          });
        }
      }).render('#paypal-button-container'); // Display payment options on your web page
    </script>

    <a style="background-color:#242647;color:#FFFFFF;border-color:#242647;font-weight:bold; padding-top:10px;padding-bottom:10px;padding-left:15px;padding-right:15px;border-radius:5px"
    href="../complete_payment">Completar pago</a>

{% endblock %}

main/templates/main/pedido_detail.html
{% extends "base.html" %}

{% block content %}
    {% if es_carrito %}
    <h3 class="title"> Carrito </h3>
    {% else %}
    <h3 class="title"> Pedido </h3>
    {% endif %}
    <div class="block">
        <h5 class="subtitle"> Información General </h5>
        <div class="content">
            <ul>
              <li> <strong>Cliente:</strong> {{ object.cliente.user_profile.user.get_username }}</li>
              <li> <strong>Fecha Creación:</strong> {{ object.fecha_creacion }}</li>
              <li> <strong>Estado:</strong> {{ object.estado }}</li>
            </ul>
        </div>
    </div>
    <div class="block">
        <h5 class="subtitle"> Detalle </h5>
        <div class="content">
            <ul>
              <!-- Agrega cada detalle del pedido -->
              {% for detalle in detalles %}
                <li>
                  {{ detalle }}
                  {% if es_carrito %}
                  <a href="{% url 'add-to-cart' product_pk=detalle.producto.pk %}" class="button is-success">
                    +
                  </a>
                  <a href="{% url 'remove-from-cart' product_pk=detalle.producto.pk %}" class="button is-danger">
                    -
                  </a>
                  {% endif %}
                </li>
              {% endfor %}
            </ul>
        </div>
    </div>
   {% if es_carrito %}
    <a href="{% url 'pedido-update' pk=object.pk %}" class='button is-info'>
      Checkout
    </a>
   {% else %}
   <div class="container">
     <h5 class="subtitle">Comuniquese con el colaborador</h5>
     <div class="row">
        {% for comment in comments %}
       <div class="col-md-8 card mb-4  mt-3 ">
         <div class="card-body">
           <div class="comments" style="padding: 10px;">
             <p class="font-weight-bold">
               {{ comment.usuario }}
               <span class=" text-muted font-weight-normal">
                 {{ comment.created_on }}
               </span>
             </p>
             {{ comment.body | linebreaks }}
           </div>
         </div>
       </div>
       {% endfor %}
     </div>
   </div>
   <a href="{% url 'registrar-comentario' pedido_pk=object.pk %}" class='button is-info'>
     Registrar comentario
   </a>
   {% endif %}
    <hr>
{% endblock %}

main/templates/main/pedido_form.html
{% extends "base.html" %}

{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '/register.css' %}">
    <h3 class="title"> Checkout </h3>

    <div class="block">
        <h5 class="subtitle"> Completa tus datos </h5>
          <!-- Muestra el formulario de pedido de compra -->
         <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Submit" class="button is-info">
        </form>
    </div>

    <hr>

{% endblock %}

main/templates/main/producto_detail.html
{% extends "base.html" %}

{% block content %}
    <h3 class="title"> {{ object.nombre }} </h3>
    <div class="columns">
       <!-- Muestra las imagenes para los productos -->
        {% for image in object.images.all %}
        <div class="column is-3">
            <figure class="image is-square">
                <a href="{{ image.image.url }}">
                    <img src="{{ image.image.url }}" alt="No hay imagen disponible">
                </a>
            </figure>
        </div>
        {% empty %}
        <div class="column content">
            <p>Aún no hay imágenes disponibles</p>
        </div>
        {% endfor %}
    </div>

    <div class="content">
        <ul>
          <li><strong>Precio:</strong> $ {{ object.precio }}</li>
          <li><strong>Descripcion:</strong> {{ object.descripcion }}</li>
          <li><strong>Categoria:</strong> {{ object.categoria.nombre }}</li>
          <li><strong>Proveedor:</strong> {{ object.proveedor }}</li>
        </ul>
    </div>
    <div class="block">
        <a href="{% url 'add-to-cart' product_pk=object.pk %}" class='button is-primary'>
          Añadir al carrito
        </a>
        <a href="{% url 'pedido-detail' %}" class='button'>
          Ver carrito
        </a>
        {% if puede_editar_producto %}
           <a href="{% url 'editar-producto' pk=object.pk %}" class='button'>
             Editar producto
           </a>
        {% endif %}
    </div>
    <hr>
{% endblock %}

main/templates/main/producto_list.html
{% extends "base.html" %}

{% block content %}
    <h3 class="title"> Productos </h3>
    <form action="{% url 'product-list' %}" method="get">
      <label>Buscar por categoria:</label>
       <input type="hidden" name="q" value="buscar_por_categoria">
       <select name="categoria" id="categoria" style="margin-bottom:24px">
           {% for categoria in categoria_list %}
           {% if categoria.nombre == categoria_selected %}
           <option value="{{ categoria.nombre }}" selected>{{ categoria.nombre }}</option>
           {% else %}
           <option value="{{ categoria.nombre }}">{{ categoria.nombre }}</option>
           {% endif %}
           {% endfor %}
      </select>
       <input type="submit" name="featured" value="Filter" />
   </form>
    <div class="columns is-multiline">
           <!-- Lista de productos -->
          {% for producto in object_list %}
          <div class="column is-4">
                <div class="card">
                    <div class="card-image">
                        <figure class="image">
                            <img src="{{ producto.images.first.image.url|default:'https://via.placeholder.com/128' }}" alt="Imagen no disponible">
                        </figure>
                    </div>
                    <div class="card-content">
                        <h6>
                            <a href="{% url 'product-detail' producto.pk %}">
                                {{ producto.nombre }}
                            </a>
                        </h6>
                        <p>$ {{ producto.precio }}</p>
                    </div>
                </div>
            </div>
          {% empty %}
              <div class="content">
                <h6>Aun no hay productos disponibles.</h6>
              </div>
          {% endfor %}
    </div>
    <hr>
{% endblock %}